language: java
before_install:
- openssl aes-256-cbc -K $encrypted_4acda2ae39ca_key -iv $encrypted_4acda2ae39ca_iv
  -in appinventor-ptpt-ed4e8cafcc91.json.enc -out appinventor/appinventor-ptpt-ed4e8cafcc91.json
  -d
- sudo apt-get -qq update
- sudo apt-get install -y libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1
before_script: cd appinventor
script:
- ant MakeAuthKey
- ant
after_success:
  - wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.48.zip -O /tmp/gae-sdk.zip
  - unzip x /tmp/gae-sdk.zip
  - export PATH=$PATH:$PWD/appengine-java-sdk-1.9.48/bin/
  - appcfg.sh -A appinventor-ptpt --service_account_json_key_file=appinventor-ptpt-ed4e8cafcc91.json update appengine/build/war/

