language: java
before_install:
- openssl aes-256-cbc -K $encrypted_4acda2ae39ca_key -iv $encrypted_4acda2ae39ca_iv
  -in appinventor-ptpt-ed4e8cafcc91.json.enc -out appinventor/appinventor-ptpt-ed4e8cafcc91.json
  -d
- sudo apt-get -qq update
- sudo apt-get install -y libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1
before_script: cd appinventor
script:
- ant MakeAuthKey
- ant
deploy:
  provider: gae
  keyfile: "appinventor-ptpt-ed4e8cafcc91.json"
  project: appinventor-ptpt
  on: pt-pt_translation
  verbosity: debug
  default: true
